# Generated by Django 6.0.3 on 2026-05-06 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Docente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("pagina", models.URLField(blank=True, null=True)),
                ("codigo", models.IntegerField(blank=True, null=True, unique=True)),
                ("grau", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Licenciatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                ("duracao", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="MakingOf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(blank=True, max_length=200, null=True)),
                ("descricao_processo", models.TextField(blank=True, null=True)),
                ("decisoes", models.TextField(blank=True, null=True)),
                ("erros", models.TextField(blank=True, null=True)),
                ("correcoes", models.TextField(blank=True, null=True)),
                ("justificacao_modelacao", models.TextField(blank=True, null=True)),
                ("uso_ia", models.TextField(blank=True, null=True)),
                ("data", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Owner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(blank=True, max_length=100, null=True)),
                ("titulo", models.CharField(blank=True, max_length=100, null=True)),
                ("bio", models.TextField(blank=True, null=True)),
                ("foto", models.ImageField(blank=True, null=True, upload_to="perfil/")),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("github", models.URLField(blank=True, null=True)),
                ("linkedin", models.URLField(blank=True, null=True)),
                ("cv", models.FileField(blank=True, null=True, upload_to="cv/")),
            ],
        ),
        migrations.CreateModel(
            name="Tecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("tipo", models.CharField(max_length=50)),
                ("descricao", models.TextField()),
                ("logo", models.ImageField(upload_to="tech/")),
                ("website", models.URLField()),
                ("nivel", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Tfc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(blank=True, max_length=300, null=True)),
                ("autores", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "orientadores",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "licenciaturas",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("ano", models.IntegerField(blank=True, null=True)),
                ("sumario", models.TextField(blank=True, null=True)),
                ("link_pdf", models.URLField(blank=True, null=True)),
                ("imagem", models.URLField(blank=True, null=True)),
                ("palavras_chave", models.TextField(blank=True, null=True)),
                ("areas", models.TextField(blank=True, null=True)),
                ("tecnologias_usadas", models.TextField(blank=True, null=True)),
                ("rating", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Universidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Formacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("instituicao", models.CharField(max_length=100)),
                ("inicio", models.DateField()),
                ("fim", models.DateField()),
                ("descricao", models.TextField()),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portofolio.owner",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UnidadeCurricular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.IntegerField(unique=True)),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                ("ano", models.IntegerField()),
                ("semestre", models.CharField(max_length=20)),
                ("ects", models.IntegerField()),
                ("imagem", models.ImageField(upload_to="ucs/")),
                (
                    "docentes",
                    models.ManyToManyField(related_name="ucs", to="portofolio.docente"),
                ),
                (
                    "licenciatura",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portofolio.licenciatura",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                ("conceitos", models.TextField()),
                ("imagem", models.ImageField(upload_to="projetos/")),
                ("video", models.URLField(blank=True)),
                ("github", models.URLField()),
                ("destaque", models.BooleanField(default=False)),
                ("data", models.DateField()),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portofolio.owner",
                    ),
                ),
                ("tecnologias", models.ManyToManyField(to="portofolio.tecnologia")),
                (
                    "unidade_curricular",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portofolio.unidadecurricular",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="licenciatura",
            name="universidade",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="portofolio.universidade",
            ),
        ),
    ]
