# Generated by Django 6.0.3 on 2026-04-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Owner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("titulo", models.CharField(max_length=100)),
                ("bio", models.TextField()),
                ("foto", models.ImageField(upload_to="perfil/")),
                ("email", models.EmailField(max_length=254)),
                ("github", models.URLField()),
                ("linkedin", models.URLField()),
                ("cv", models.FileField(upload_to="cv/")),
            ],
        ),
    ]
