# Generated by Django 6.0.3 on 2026-05-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portofolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="unidadecurricular",
            name="objetivos",
            field=models.TextField(blank=True, null=True),
        ),
    ]
