# Generated by Django 6.0.3 on 2026-04-09 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portofolio", "0002_docente_licenciatura_tecnologia_universidade_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TFC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("autor", models.CharField(max_length=100)),
                ("ano", models.IntegerField()),
                ("resumo", models.TextField()),
                ("interesse", models.IntegerField()),
            ],
        ),
    ]
