# Generated by Django 6.0.3 on 2026-07-05 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portofolio", "0002_unidadecurricular_objetivos"),
    ]

    operations = [
        migrations.CreateModel(
            name="Competencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("nivel", models.CharField(max_length=50)),
                ("descricao", models.TextField()),
            ],
        ),
    ]
