# Generated by Django 6.0.3 on 2026-04-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portofolio", "0003_tfc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tfc",
            name="autor",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
