# Generated by Django 6.0.3 on 2026-07-05 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portofolio", "0003_competencia"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projeto",
            name="data",
        ),
        migrations.RemoveField(
            model_name="projeto",
            name="destaque",
        ),
        migrations.RemoveField(
            model_name="projeto",
            name="owner",
        ),
        migrations.AddField(
            model_name="projeto",
            name="competencias",
            field=models.ManyToManyField(blank=True, to="portofolio.competencia"),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="github",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="tecnologias",
            field=models.ManyToManyField(blank=True, to="portofolio.tecnologia"),
        ),
    ]
