# Generated by Django 6.0.3 on 2026-07-06 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portofolio", "0004_remove_projeto_data_remove_projeto_destaque_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="owner",
            name="titulo",
        ),
    ]
