# Generated by Django 6.0.3 on 2026-04-09 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portofolio", "0004_alter_tfc_autor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tfc",
            name="autor",
        ),
        migrations.RemoveField(
            model_name="tfc",
            name="interesse",
        ),
        migrations.RemoveField(
            model_name="tfc",
            name="resumo",
        ),
        migrations.AddField(
            model_name="tfc",
            name="areas",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tfc",
            name="autores",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="tfc",
            name="imagem",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tfc",
            name="licenciaturas",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="tfc",
            name="link_pdf",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tfc",
            name="orientadores",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="tfc",
            name="palavras_chave",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tfc",
            name="rating",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tfc",
            name="sumario",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tfc",
            name="tecnologias_usadas",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="ano",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="titulo",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
