# Generated by Django 6.0.3 on 2026-07-06 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portofolio", "0005_remove_owner_titulo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="formacao",
            name="owner",
        ),
    ]
