# Generated by Django 6.0.3 on 2026-04-11 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portofolio", "0005_remove_tfc_autor_remove_tfc_interesse_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MakingOf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(blank=True, max_length=200, null=True)),
                ("descricao_processo", models.TextField(blank=True, null=True)),
                ("decisoes", models.TextField(blank=True, null=True)),
                ("erros", models.TextField(blank=True, null=True)),
                ("correcoes", models.TextField(blank=True, null=True)),
                ("justificacao_modelacao", models.TextField(blank=True, null=True)),
                ("uso_ia", models.TextField(blank=True, null=True)),
                ("data", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
