# Generated by Django 6.0.3 on 2026-07-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portofolio", "0006_remove_formacao_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="makingof",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="making-of/"),
        ),
    ]
