# Generated by Django 6.0.3 on 2026-06-03 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("genero", models.CharField(max_length=50)),
                ("ano_formacao", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Instrumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("tipo", models.CharField(max_length=50)),
                ("naipe", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Concerto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("local", models.CharField(max_length=100)),
                ("data", models.DateField()),
                ("capacidade", models.PositiveIntegerField()),
                (
                    "banda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concertos",
                        to="banda.banda",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Musico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("idade", models.PositiveIntegerField()),
                ("instrumentos", models.ManyToManyField(to="banda.instrumento")),
            ],
        ),
    ]
