# Generated by Django 6.0.3 on 2026-06-21 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banda", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="banda",
            name="musicos",
            field=models.ManyToManyField(
                blank=True, related_name="bandas", to="banda.musico"
            ),
        ),
        migrations.AlterField(
            model_name="musico",
            name="instrumentos",
            field=models.ManyToManyField(
                blank=True, related_name="musicos", to="banda.instrumento"
            ),
        ),
    ]
